version: '3'

services:
  database:
    container_name: mysql
    build: ./database
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql

  php-fpm:
    container_name: php-fpm
    build: ./php-fpm
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
    volumes:
      - ..:/var/www
      - ./wait-for-it.sh:/usr/bin/wait-for-it

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ..:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
      - ./wait-for-it.sh:/usr/bin/wait-for-it
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"

  cypress:
    container_name: cypress
    build: ./e2e
    depends_on:
      - nginx
    volumes:
      - ../cypress:/var/www/cypress
      - ./e2e/cypress.json:/var/www/cypress.json
      - ./wait-for-it.sh:/usr/bin/wait-for-it